version: "3"

dotenv: [".env"]

vars:
  REGISTRY: "ghcr.io/qrave1/roomspeak"
  COMPOSE_FILE: deploy/docker-compose.yml
  BUILD_TIMESTAMP:
    sh: date +%Y_%m_%d_%H_%M_%S

tasks:
  build:
    desc: Build Docker image with timestamp tag
    cmds:
      - docker build -t {{.REGISTRY}}:{{.BUILD_TIMESTAMP}} .
      - docker tag {{.REGISTRY}}:{{.BUILD_TIMESTAMP}} {{.REGISTRY}}:latest

  push:
    desc: Build and push Docker image to registry
    deps: [build]
    cmds:
      - docker push {{.REGISTRY}}:{{.BUILD_TIMESTAMP}}
      - docker push {{.REGISTRY}}:latest

  deploy:
    desc: Build, push, update deployment.yaml and apply
    deps: [push]
  #    cmds: TODO

  # Migrations
  migrate:create:
    desc: Create a new goose migration
    dir: internal/infra/postgres/migrations
    cmds:
      - goose create {{.CLI_ARGS}} sql

  # Docker Compose
  infra:
    desc: Run Infrastructure
    cmds:
      - echo "Start dev environment"
      - docker compose --file {{.COMPOSE_FILE}} --profile infra up -d

  app:
    desc: Run Application
    cmds:
      - echo "Start dev app"
      - docker compose --file {{.COMPOSE_FILE}} --profile app up -d --build
