version: '3'

vars:
  REGISTRY: "ghcr.io/qrave1/roomspeak"
  BUILD_TIMESTAMP:
    sh: date +%Y_%m_%d_%H_%M_%S

tasks:
  docker-build:
    desc: Build Docker image with timestamp tag
    cmds:
      - docker build -t {{.REGISTRY}}:{{.BUILD_TIMESTAMP}} .
      - docker tag {{.REGISTRY}}:{{.BUILD_TIMESTAMP}} {{.REGISTRY}}:latest

  docker-push:
    desc: Build and push Docker image to registry
    deps: [ docker-build ]
    cmds:
      - docker push {{.REGISTRY}}:{{.BUILD_TIMESTAMP}}
      - docker push {{.REGISTRY}}:latest

  deploy:
    desc: Build, push, update deployment.yaml and apply
    deps: [ docker-push ]
    cmds:
      # Подставляем новый тег в deployment.yaml (перезапись на диске)
      - IMAGE="{{.REGISTRY}}:{{.BUILD_TIMESTAMP}}" yq eval -i '.spec.template.spec.containers[0].image = strenv(IMAGE)' k8s/deployment.yaml

      # Применяем обновлённый манифест
      - kubectl apply -f k8s/deployment.yaml
