version: "3"

dotenv: [ ".env" ]

vars:
  REGISTRY: "ghcr.io/qrave1/roomspeak"
  COMPOSE_FILE: deploy/docker-compose.yml
  BUILD_TIMESTAMP:
    sh: date +%Y_%m_%d_%H_%M_%S
  BACK_TAG: "{{.REGISTRY}}:{{.BUILD_TIMESTAMP}}_backend"
  FRONT_TAG: "{{.REGISTRY}}:{{.BUILD_TIMESTAMP}}_frontend"

tasks:
  back:build:
    desc: Build Docker image with timestamp tag
    cmds:
      - docker build -t {{.BACK_TAG}} .

  back:push:
    desc: Build and push Docker image to registry
    deps: [ back:build ]
    cmds:
      - docker push {{.BACK_TAG}}

  back:deploy:
    desc: Build, push, update deployment.yaml and apply
    deps: [ back:push ]
  #    cmds: TODO

  # Migrations
  migrate:create:
    desc: Create a new goose migration
    dir: internal/infra/postgres/migrations
    cmds:
      - goose create {{.CLI_ARGS}} sql

  # Docker Compose
  infra:
    desc: Run Infrastructure
    cmds:
      - echo "Start dev environment"
      - docker compose --file {{.COMPOSE_FILE}} --profile infra up -d

  app:
    desc: Run Application
    cmds:
      - echo "Start dev app"
      - docker compose --file {{.COMPOSE_FILE}} --profile app up -d --build

  # FRONTEND
  front:run:
    desc: Run Vue Frontend
    dir: web-vue/
    cmds:
      - npm run dev

  front:build:
    desc: Build Docker image with timestamp tag
    dir: web-vue/
    cmds:
      - docker build -t {{.FRONT_TAG}} .

  front:push:
    desc: Build Docker image with timestamp tag
    dir: web-vue/
    deps: [ front:build ]
    cmds:
      - docker push {{.FRONT_TAG}}