version: '3'

vars:
  REGISTRY: "ghcr.io/qrave1/roomspeak"
  BUILD_TIMESTAMP:
    sh: date +%Y_%m_%d_%H_%M_%S

tasks:
  build:
    desc: Build Docker image with timestamp tag
    cmds:
      - docker build -t {{.REGISTRY}}:{{.BUILD_TIMESTAMP}} .
      - docker tag {{.REGISTRY}}:{{.BUILD_TIMESTAMP}} {{.REGISTRY}}:latest

  push:
    desc: Build and push Docker image to registry
    deps: [ build ]
    cmds:
      - docker push {{.REGISTRY}}:{{.BUILD_TIMESTAMP}}
      - docker push {{.REGISTRY}}:latest

  deploy:
    desc: Build, push, update deployment.yaml and apply
    deps: [ push ]
    cmds:

