apiVersion: v1
kind: Secret
metadata:
  namespace: roomspeak-prod
  name: turn-secret
type: Opaque
stringData:
  TURN_URL: "relay1.expressturn.com:3480"
  TURN_USERNAME: "user"
  TURN_PASSWORD: "password"
