services:
  roomspeak:
    image: ghcr.io/qrave1/roomspeak:2025_09_04_18_35_36
    container_name: roomspeak-backend
    restart: unless-stopped

    # labels для traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.example.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"

    ports:
      - "3000:3000"
    networks:
      - default
    env_file: .env
